[Service]
  Port = "8000"
  Environment = "develop"
[Postgres]
  dbname = "rest_example"
  host = "localhost"
  port = "5432"
  user = "postgres"
  pass = "1234"
[Mysql]
  dbname = "rest_example"
  host = "localhost"
  port = "3306"
  user = "root"
  pass = ""
[Mongo]
  dbname = "rest_example"
  host = "localhost:27017"
  auth = ""
  user = ""
  pass = ""
[Redis]
  database = "0"
  host = "localhost"
  port = "6379"
  pass = ""
[Admin]
  email = "admin@xenonstack.com"
  pass = "admin"
[JWT]
  PrivateKey = "abc"
[Jaeger]
  Host = "localhost"
  Port = "6831"
