// Code generated by protoc-gen-go. DO NOT EDIT.
// source: micro-service1.proto

package microservice1

import (
	context "context"
	fmt "fmt"
	pb "git.xenonstack.com/util/golang-boilerplate/grpc-example/micro-service2/pb"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//requests and replies
type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a80ed75f469548, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type UserDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                int64    `protobuf:"varint,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetail) Reset()         { *m = UserDetail{} }
func (m *UserDetail) String() string { return proto.CompactTextString(m) }
func (*UserDetail) ProtoMessage()    {}
func (*UserDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a80ed75f469548, []int{1}
}

func (m *UserDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetail.Unmarshal(m, b)
}
func (m *UserDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetail.Marshal(b, m, deterministic)
}
func (m *UserDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetail.Merge(m, src)
}
func (m *UserDetail) XXX_Size() int {
	return xxx_messageInfo_UserDetail.Size(m)
}
func (m *UserDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetail.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetail proto.InternalMessageInfo

func (m *UserDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserDetail) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

type UserDetailInfo struct {
	UserDetail           *UserDetail  `protobuf:"bytes,1,opt,name=userDetail,proto3" json:"userDetail,omitempty"`
	UserInfo             *pb.UserInfo `protobuf:"bytes,2,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserDetailInfo) Reset()         { *m = UserDetailInfo{} }
func (m *UserDetailInfo) String() string { return proto.CompactTextString(m) }
func (*UserDetailInfo) ProtoMessage()    {}
func (*UserDetailInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a80ed75f469548, []int{2}
}

func (m *UserDetailInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailInfo.Unmarshal(m, b)
}
func (m *UserDetailInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailInfo.Marshal(b, m, deterministic)
}
func (m *UserDetailInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailInfo.Merge(m, src)
}
func (m *UserDetailInfo) XXX_Size() int {
	return xxx_messageInfo_UserDetailInfo.Size(m)
}
func (m *UserDetailInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailInfo proto.InternalMessageInfo

func (m *UserDetailInfo) GetUserDetail() *UserDetail {
	if m != nil {
		return m.UserDetail
	}
	return nil
}

func (m *UserDetailInfo) GetUserInfo() *pb.UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type AddReply struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReply) Reset()         { *m = AddReply{} }
func (m *AddReply) String() string { return proto.CompactTextString(m) }
func (*AddReply) ProtoMessage()    {}
func (*AddReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a80ed75f469548, []int{3}
}

func (m *AddReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReply.Unmarshal(m, b)
}
func (m *AddReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReply.Marshal(b, m, deterministic)
}
func (m *AddReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReply.Merge(m, src)
}
func (m *AddReply) XXX_Size() int {
	return xxx_messageInfo_AddReply.Size(m)
}
func (m *AddReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddReply proto.InternalMessageInfo

func (m *AddReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *AddReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "microservice1.EmptyRequest")
	proto.RegisterType((*UserDetail)(nil), "microservice1.UserDetail")
	proto.RegisterType((*UserDetailInfo)(nil), "microservice1.UserDetailInfo")
	proto.RegisterType((*AddReply)(nil), "microservice1.AddReply")
}

func init() { proto.RegisterFile("micro-service1.proto", fileDescriptor_a0a80ed75f469548) }

var fileDescriptor_a0a80ed75f469548 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4b, 0x4b, 0xf3, 0x40,
	0x14, 0x6d, 0xbe, 0xcf, 0x47, 0x7b, 0xab, 0x59, 0x0c, 0x85, 0xd6, 0x8a, 0x50, 0xb2, 0xea, 0xa6,
	0x09, 0xa6, 0x20, 0xe8, 0xae, 0xe0, 0x03, 0x37, 0x2e, 0x06, 0xdc, 0x0a, 0xd3, 0xe4, 0x1a, 0x83,
	0xf3, 0x72, 0x66, 0x2a, 0xed, 0xce, 0x3f, 0xe3, 0xff, 0x94, 0x4c, 0x68, 0x9b, 0x16, 0xba, 0xcb,
	0x39, 0xf7, 0x9e, 0xc7, 0xcd, 0x40, 0x4f, 0x94, 0x99, 0x51, 0x13, 0x8b, 0xe6, 0xbb, 0xcc, 0xf0,
	0x3a, 0xd6, 0x46, 0x39, 0x45, 0xce, 0x3d, 0xbb, 0x26, 0x87, 0x6f, 0x45, 0xe9, 0xe2, 0x25, 0x4a,
	0x25, 0xad, 0x63, 0xd9, 0x67, 0x9c, 0x29, 0x91, 0x2c, 0x5c, 0xc9, 0x93, 0x42, 0x71, 0x26, 0x8b,
	0xc9, 0x5c, 0x95, 0x1c, 0x8d, 0xe6, 0xcc, 0x61, 0x52, 0x18, 0x9d, 0x4d, 0x70, 0xc9, 0x84, 0xe6,
	0x98, 0xec, 0x98, 0xa7, 0x89, 0x9e, 0xef, 0x31, 0x75, 0x5c, 0x14, 0xc2, 0xd9, 0x83, 0xd0, 0x6e,
	0x45, 0xf1, 0x6b, 0x81, 0xd6, 0x45, 0x37, 0x00, 0xaf, 0x16, 0xcd, 0x3d, 0x3a, 0x56, 0x72, 0x42,
	0xe0, 0x48, 0x32, 0x81, 0x83, 0x60, 0x14, 0x8c, 0x3b, 0xd4, 0x7f, 0x93, 0x1e, 0x1c, 0xeb, 0x0f,
	0x25, 0x71, 0xf0, 0x6f, 0x14, 0x8c, 0xff, 0xd3, 0x1a, 0x44, 0x3f, 0x01, 0x84, 0x5b, 0xe1, 0xb3,
	0x7c, 0x57, 0xe4, 0x16, 0x60, 0xb1, 0x61, 0xbc, 0x45, 0x37, 0xbd, 0x88, 0x77, 0xce, 0x8b, 0xb7,
	0x12, 0xda, 0x58, 0x26, 0x53, 0x68, 0x57, 0xa8, 0xb2, 0xf1, 0x31, 0xdd, 0xb4, 0xbf, 0x23, 0x4c,
	0xbd, 0xb0, 0x1a, 0xd3, 0xcd, 0x62, 0x74, 0x07, 0xed, 0x59, 0x9e, 0x53, 0xd4, 0x7c, 0x55, 0x95,
	0x44, 0x63, 0x94, 0xf1, 0xb1, 0x6d, 0x5a, 0x03, 0x32, 0x80, 0x53, 0x81, 0xd6, 0xb2, 0xa2, 0x2e,
	0xdf, 0xa1, 0x6b, 0x98, 0xfe, 0x06, 0xd0, 0xdd, 0x76, 0xb1, 0xe4, 0x11, 0xc2, 0x59, 0x9e, 0x37,
	0x99, 0xc3, 0xcd, 0x87, 0xfd, 0xbd, 0xd1, 0xba, 0x45, 0xd4, 0x22, 0x2f, 0x10, 0x3e, 0xa1, 0x6b,
	0xfa, 0x5c, 0xee, 0x2d, 0x37, 0xff, 0xfe, 0xf0, 0xea, 0x60, 0x88, 0xbf, 0xb0, 0x35, 0x3f, 0xf1,
	0xaf, 0x36, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x27, 0x55, 0x40, 0x3c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserDetailsClient is the client API for UserDetails service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserDetailsClient interface {
	AddUserDetails(ctx context.Context, in *UserDetail, opts ...grpc.CallOption) (*AddReply, error)
	GetUserDetails(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*UserDetailInfo, error)
}

type userDetailsClient struct {
	cc *grpc.ClientConn
}

func NewUserDetailsClient(cc *grpc.ClientConn) UserDetailsClient {
	return &userDetailsClient{cc}
}

func (c *userDetailsClient) AddUserDetails(ctx context.Context, in *UserDetail, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := c.cc.Invoke(ctx, "/microservice1.UserDetails/AddUserDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDetailsClient) GetUserDetails(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*UserDetailInfo, error) {
	out := new(UserDetailInfo)
	err := c.cc.Invoke(ctx, "/microservice1.UserDetails/GetUserDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDetailsServer is the server API for UserDetails service.
type UserDetailsServer interface {
	AddUserDetails(context.Context, *UserDetail) (*AddReply, error)
	GetUserDetails(context.Context, *EmptyRequest) (*UserDetailInfo, error)
}

func RegisterUserDetailsServer(s *grpc.Server, srv UserDetailsServer) {
	s.RegisterService(&_UserDetails_serviceDesc, srv)
}

func _UserDetails_AddUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailsServer).AddUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservice1.UserDetails/AddUserDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailsServer).AddUserDetails(ctx, req.(*UserDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDetails_GetUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailsServer).GetUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservice1.UserDetails/GetUserDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailsServer).GetUserDetails(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserDetails_serviceDesc = grpc.ServiceDesc{
	ServiceName: "microservice1.UserDetails",
	HandlerType: (*UserDetailsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUserDetails",
			Handler:    _UserDetails_AddUserDetails_Handler,
		},
		{
			MethodName: "GetUserDetails",
			Handler:    _UserDetails_GetUserDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "micro-service1.proto",
}
