// Code generated by protoc-gen-go. DO NOT EDIT.
// source: micro-service2.proto

package microservice2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//requests and replies
type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbabdd8f3473d440, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type Address struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Postal               int64    `protobuf:"varint,4,opt,name=postal,proto3" json:"postal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbabdd8f3473d440, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetPostal() int64 {
	if m != nil {
		return m.Postal
	}
	return 0
}

type Interests struct {
	Interest             string   `protobuf:"bytes,1,opt,name=interest,proto3" json:"interest,omitempty"`
	Priority             int64    `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interests) Reset()         { *m = Interests{} }
func (m *Interests) String() string { return proto.CompactTextString(m) }
func (*Interests) ProtoMessage()    {}
func (*Interests) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbabdd8f3473d440, []int{2}
}

func (m *Interests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interests.Unmarshal(m, b)
}
func (m *Interests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interests.Marshal(b, m, deterministic)
}
func (m *Interests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interests.Merge(m, src)
}
func (m *Interests) XXX_Size() int {
	return xxx_messageInfo_Interests.Size(m)
}
func (m *Interests) XXX_DiscardUnknown() {
	xxx_messageInfo_Interests.DiscardUnknown(m)
}

var xxx_messageInfo_Interests proto.InternalMessageInfo

func (m *Interests) GetInterest() string {
	if m != nil {
		return m.Interest
	}
	return ""
}

func (m *Interests) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type UserInfo struct {
	Address              *Address     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Interests            []*Interests `protobuf:"bytes,2,rep,name=interests,proto3" json:"interests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbabdd8f3473d440, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *UserInfo) GetInterests() []*Interests {
	if m != nil {
		return m.Interests
	}
	return nil
}

type UserInfoReply struct {
	Error                bool      `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	UserInfo             *UserInfo `protobuf:"bytes,2,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoReply) Reset()         { *m = UserInfoReply{} }
func (m *UserInfoReply) String() string { return proto.CompactTextString(m) }
func (*UserInfoReply) ProtoMessage()    {}
func (*UserInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbabdd8f3473d440, []int{4}
}

func (m *UserInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoReply.Unmarshal(m, b)
}
func (m *UserInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoReply.Marshal(b, m, deterministic)
}
func (m *UserInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoReply.Merge(m, src)
}
func (m *UserInfoReply) XXX_Size() int {
	return xxx_messageInfo_UserInfoReply.Size(m)
}
func (m *UserInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoReply proto.InternalMessageInfo

func (m *UserInfoReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *UserInfoReply) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type AddReply struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReply) Reset()         { *m = AddReply{} }
func (m *AddReply) String() string { return proto.CompactTextString(m) }
func (*AddReply) ProtoMessage()    {}
func (*AddReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbabdd8f3473d440, []int{5}
}

func (m *AddReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReply.Unmarshal(m, b)
}
func (m *AddReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReply.Marshal(b, m, deterministic)
}
func (m *AddReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReply.Merge(m, src)
}
func (m *AddReply) XXX_Size() int {
	return xxx_messageInfo_AddReply.Size(m)
}
func (m *AddReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddReply proto.InternalMessageInfo

func (m *AddReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *AddReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "microservice2.EmptyRequest")
	proto.RegisterType((*Address)(nil), "microservice2.Address")
	proto.RegisterType((*Interests)(nil), "microservice2.Interests")
	proto.RegisterType((*UserInfo)(nil), "microservice2.UserInfo")
	proto.RegisterType((*UserInfoReply)(nil), "microservice2.UserInfoReply")
	proto.RegisterType((*AddReply)(nil), "microservice2.AddReply")
}

func init() { proto.RegisterFile("micro-service2.proto", fileDescriptor_bbabdd8f3473d440) }

var fileDescriptor_bbabdd8f3473d440 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x5b, 0x9b, 0x74, 0x6a, 0x15, 0x86, 0xd2, 0x2e, 0xd5, 0x43, 0xd9, 0x53, 0x2f,
	0x16, 0x49, 0xc1, 0x83, 0xb7, 0x22, 0xa2, 0x3d, 0xba, 0xe0, 0xc5, 0x5b, 0x4c, 0x46, 0x09, 0x34,
	0xd9, 0xb8, 0xbb, 0x15, 0xf2, 0xa7, 0xfc, 0x8d, 0xd2, 0x4d, 0x36, 0x6a, 0xa4, 0xde, 0xf2, 0x5e,
	0x66, 0xbf, 0x79, 0xb3, 0x3b, 0x30, 0xce, 0xd2, 0x58, 0xc9, 0x4b, 0x4d, 0xea, 0x23, 0x8d, 0x29,
	0x5c, 0x16, 0x4a, 0x1a, 0x89, 0x23, 0xeb, 0x3a, 0x93, 0x9f, 0xc2, 0xc9, 0x5d, 0x56, 0x98, 0x52,
	0xd0, 0xfb, 0x8e, 0xb4, 0xe1, 0x04, 0xfe, 0x3a, 0x49, 0x14, 0x69, 0x8d, 0x08, 0xbd, 0x38, 0x35,
	0x25, 0xf3, 0xe6, 0xde, 0x62, 0x20, 0xec, 0x37, 0x8e, 0xe1, 0x58, 0x9b, 0xc8, 0x10, 0xeb, 0x58,
	0xb3, 0x12, 0xc8, 0xc0, 0x8f, 0xe5, 0x2e, 0x37, 0xaa, 0x64, 0x5d, 0xeb, 0x3b, 0x89, 0x13, 0xe8,
	0x17, 0x52, 0x9b, 0x68, 0xcb, 0x7a, 0x73, 0x6f, 0xd1, 0x15, 0xb5, 0xe2, 0xb7, 0x30, 0xd8, 0xe4,
	0x86, 0x14, 0x69, 0xa3, 0x71, 0x06, 0x41, 0x5a, 0x8b, 0xba, 0x59, 0xa3, 0xf7, 0xff, 0x0a, 0x95,
	0x4a, 0xb5, 0x0f, 0xd2, 0xb1, 0x88, 0x46, 0x73, 0x03, 0xc1, 0x93, 0x26, 0xb5, 0xc9, 0x5f, 0x25,
	0x5e, 0x81, 0x1f, 0x55, 0xb9, 0x2d, 0x62, 0x18, 0x4e, 0x96, 0xbf, 0x06, 0x5d, 0xd6, 0x53, 0x09,
	0x57, 0x86, 0xd7, 0x30, 0x70, 0x5d, 0x34, 0xeb, 0xcc, 0xbb, 0x8b, 0x61, 0xc8, 0x5a, 0x67, 0x9a,
	0x88, 0xe2, 0xbb, 0x94, 0x3f, 0xc3, 0xc8, 0x75, 0x15, 0x54, 0x6c, 0xed, 0x9d, 0x90, 0x52, 0x52,
	0xd9, 0xc6, 0x81, 0xa8, 0x04, 0xae, 0x20, 0xd8, 0xd5, 0x65, 0x36, 0xf8, 0x30, 0x9c, 0xb6, 0xe8,
	0x0d, 0xa5, 0x29, 0xe4, 0x37, 0x10, 0xac, 0x93, 0xe4, 0x3f, 0x2c, 0x03, 0x3f, 0x23, 0xad, 0xa3,
	0x37, 0xf7, 0x04, 0x4e, 0x86, 0x9f, 0x1e, 0x9c, 0x39, 0xa4, 0xca, 0x22, 0x93, 0xca, 0x1c, 0x1f,
	0x00, 0xd7, 0x49, 0xd2, 0x76, 0x0f, 0x05, 0x99, 0x4d, 0xff, 0xde, 0x99, 0xcd, 0xc2, 0x8f, 0xf0,
	0x11, 0xf0, 0x9e, 0x4c, 0x9b, 0x74, 0xde, 0x3a, 0xf0, 0x73, 0x95, 0x66, 0x17, 0x87, 0xe6, 0xad,
	0x90, 0x2f, 0x7d, 0xbb, 0x90, 0xab, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0x4e, 0x31, 0x4d,
	0xa8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserInformationClient is the client API for UserInformation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserInformationClient interface {
	AddUserInformation(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*AddReply, error)
	GetUserInformation(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*UserInfoReply, error)
}

type userInformationClient struct {
	cc *grpc.ClientConn
}

func NewUserInformationClient(cc *grpc.ClientConn) UserInformationClient {
	return &userInformationClient{cc}
}

func (c *userInformationClient) AddUserInformation(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := c.cc.Invoke(ctx, "/microservice2.UserInformation/AddUserInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInformationClient) GetUserInformation(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*UserInfoReply, error) {
	out := new(UserInfoReply)
	err := c.cc.Invoke(ctx, "/microservice2.UserInformation/GetUserInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInformationServer is the server API for UserInformation service.
type UserInformationServer interface {
	AddUserInformation(context.Context, *UserInfo) (*AddReply, error)
	GetUserInformation(context.Context, *EmptyRequest) (*UserInfoReply, error)
}

func RegisterUserInformationServer(s *grpc.Server, srv UserInformationServer) {
	s.RegisterService(&_UserInformation_serviceDesc, srv)
}

func _UserInformation_AddUserInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInformationServer).AddUserInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservice2.UserInformation/AddUserInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInformationServer).AddUserInformation(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInformation_GetUserInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInformationServer).GetUserInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservice2.UserInformation/GetUserInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInformationServer).GetUserInformation(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInformation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "microservice2.UserInformation",
	HandlerType: (*UserInformationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUserInformation",
			Handler:    _UserInformation_AddUserInformation_Handler,
		},
		{
			MethodName: "GetUserInformation",
			Handler:    _UserInformation_GetUserInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "micro-service2.proto",
}
