[Service]
  Port = "8000"
  Environment = "grpc"
[Mongo]
  dbname = "grpc_example"
  host = "localhost:27017"
  auth = ""
  user = ""
  pass = ""
[Redis]
  database = "0"
  host = "localhost"
  port = "6379"
  pass = ""
[JWT]
  PrivateKey = "abc"
[Jaeger]
  Host = "localhost"
  Port = "6831"
