[Service]
  Port = "8000"
  Environment = "develop"
[Postgres]
  dbname = "graphql_example"
  host = "localhost"
  port = "5432"
  user = "postgres"
  pass = "1234"
[Redis]
  database = "0"
  host = "localhost"
  port = "6379"
  pass = ""
[Admin]
  email = "admin@xenonstack.com"
  pass = "admin"
[JWT]
  PrivateKey = "abc"
[Jaeger]
  Host = "localhost"
  Port = "6831"
