// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_example

type NewAddress struct {
	Country string `json:"country"`
	State   string `json:"state"`
	Zip     int    `json:"zip"`
}

type NewUser struct {
	Name     *string `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
}
