[Service]
  Port = "8000"
  Environment = "http"
[OtherServices]
  MicroService2 = "locahost:7002"
[Mysql]
  dbname = "rest_example"
  host = "localhost"
  port = "3306"
  user = "root"
  pass = ""
[Redis]
  database = "0"
  host = "localhost"
  port = "6379"
  pass = ""
[JWT]
  PrivateKey = "abc"
[Jaeger]
  Host = "localhost"
  Port = "6831"
